<?php

namespace Edu\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FollowadvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FollowadvertRepository extends EntityRepository
{
}
