<?php

namespace Edu\FormaBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends EntityRepository
{
    public function getAdvertWithCategories(array $categoryNames){
        $qb = $this
            ->createQueryBuilder('a')
            ->Join('a.categories', 'c')
            ->addSelect('c');

        $qb->where($qb->expr()->in('c.name', $categoryNames));

        return $qb->getQuery()->getResult();
    }
    public function getAdverts($page, $nbPerPage)
    {
        $query = $this->createQueryBuilder('a')
            ->leftJoin('a.categories', 'c')
            ->addSelect('c')
            ->leftJoin('a.image', 'i')
            ->addSelect('i')
            ->orderBy('a.date', 'DESC')
            ->getQuery();

        $query
            // On définit l'annonce à partir de laquelle commencer la liste
            ->setFirstResult(($page-1) * $nbPerPage)
            // Ainsi que le nombre d'annonce à afficher sur une page
            ->setMaxResults($nbPerPage)
        ;

        return new Paginator($query, true);
    }

    public function getPublishedQueryBuilder()
    {
        return $this
            ->createQueryBuilder('a')
            ->where('a.published = :published')
            ->setParameter('published', true)
            ;
    }
}
