edu_core_homepage:
    path:     /
    defaults: { _controller: EduCoreBundle:Default:index }

edu_core_contact:
    path:     /contact
    defaults: { _controller: EduCoreBundle:Default:contact }

edu_core_beauthor:
    path:     /author
    defaults: { _controller: EduCoreBundle:Default:author }

edu_core_recherche:
    path:     /recherche
    defaults: { _controller: EduCoreBundle:Default:recherche }

edu_core_user:
    path:     /user/{recherche}/{page}
    defaults: { _controller: EduCoreBundle:Default:user, recherche: nothing, page: 1 }